server:
  port: 5001
spring:
  security:
    user:
      name: hhcao
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
